- include_vars: "{{ ansible_os_family|lower }}.yml"
  ignore_errors: true
- include_vars: "{{ ansible_distribution|lower }}.yml"
  ignore_errors: true
- include_vars: "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version|lower }}.yml"
  ignore_errors: true
